### ISSUE TITLE
Add Topic Coordinate Calculator

### ISSUE THREAD

**Issue by avkoehl** [hugomailhot/corpus-explorer#15]
Motivation 
===
For the scatter plot visualization we need the x and y coordinates of each topic. This is only computed once for the visualization.
First we start with computing a dissimilarity matrix of the topic terms using [Jensen Shannon Divergence](https://en.wikipedia.org/wiki/Jensen%E2%80%93Shannon_divergence).
Then, given the dissimilarity matrix we apply some method of multidimensional scaling to reduce it to two dimensions. 
For now we will use PCA, but in the future we may want to test TSNE.

Deliverable 
===
A submodule that computes an x and y coordinate for each topic.

**input**

+ topic_terms matrix (numpy array ntopics x nterms) 

**output**

+ topic_coordinates (numpy array 2 x ntopics)

**Comment by hugomailhot** [comment]
I added T-SNE too as an option.

In the future, to properly use T-SNE, we might want to allow the user to control T-SNE hyperparams. For now the fit-transformer for it is properly imported and callable, and we can pass a set of keyword arguments to it later if needed. These kwargs could be specified through the user interface by the user, a bit like on this website: https://distill.pub/2016/misread-tsne/
