### ISSUE TITLE
Research Interactive Visualization Options

### ISSUE THREAD

**Issue by avkoehl** [hugomailhot/corpus-explorer#17]
Motivation
===
The whole ida of the visualization is to view changes based on different document filtering conditions. I.e how do the topic proportions change depending on the set of documents we are looking at.
We need some way for the user to define the conditions they want to use to filter the documents.
Then the documents are filtered, topic proportions are recalculated and the plot is regenerated/updated.

The purpose of this issue is to research different ways of doing this in python. 
One option is a [flask](https://www.palletsprojects.com/p/flask/) webapp. 
We could alternatively do this as a jupyter notebook?
Probably many other ways.

Deliverable
===
A report on the pros and cons of each method.
We then combine that report with our understanding of how we would like users to use this project to pick a method.

**Comment by hugomailhot** [comment]
We realized that Plot.ly covers all of our current needs, so we're good for now.

**Comment by avkoehl** [comment]
We realized Plot.ly didn't quite cover all our needs but Dash will.
