### ISSUE TITLE
Add Update Scatter Plot Method

### ISSUE THREAD

**Issue by avkoehl** [hugomailhot/corpus-explorer#18]
Motivation 
===
We need a method that updates the visualization when the conditions of the subset changes.
Until we have determined a good way of making an interactive visualization (#17 ) we still want a function (the deliverable of this issue) for testing.

Deliverable 
===
A submodule that updates a given plotly scatter plot to change the sizes of the markers.

**input**

+ plotly plot
+ topic_proportions

**output**

+ updated plotly plot

**Comment by hugomailhot** [comment]
[Relevant Plotly documentation](https://plot.ly/python/creating-and-updating-figures/)

It sounds like we can do the following:

1. Create an empty Figure object
2. Add a trace to it (an example of trace is `plotly.graph_objects.Scatter`), and ensure we can refer to it later by some property (for instance its name)
3. Update the trace properties with a new `topic_proportions` vector ([relevant doc](https://plot.ly/python/creating-and-updating-figures/#overwrite-existing-properties-when-using-update-methods))

**Comment by hugomailhot** [comment]
A minimal example of this would be to add a widget where the user can specify some numeric value, and have the marker size be multiplied by what the user inputs.

I'll update `full_run.py` to include this interaction, which will close this issue.

**Comment by hugomailhot** [comment]
https://stackoverflow.com/questions/51367567/interactive-plot-with-slider-using-plotly

A likely solution.

Apparently we can't have interaction if we just export the HTML.

**Comment by avkoehl** [comment]
Looks like based on #17 we will be using Dash for this. This has a couple implications: 

- the dash app needs access to the dataframe
- the users can subset the corpus straight from the dataframe in the dash app
- the dash app will call the relevant python code to recompute the topic proportions
- the dash app will update the graph

@hugomailhot we on the same page?

**Comment by hugomailhot** [comment]
Yep, all of the above is correct!
